apiVersion: v1
kind: Pod
metadata:
  name: testpmd
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
{
"name": "sriov-net-enp5s0f0-vfiopci",
"mac": "20:04:0f:f1:88:01",
"ips": ["192.168.109.10/24"]
}
]'
spec:
  containers:
  - name: testpmd
    image: registry.example.com:5000/testpmd
    env:
      - name: PCI_DEVICE_FILTER
        value: "PCIDEVICE_OPENSHIFT_IO"
      - name: IP_ADDRESS
        value: "192.168.109.10"
    imagePullPolicy: Always
    command: ["/bin/bash", "-c", "/entrypoint.sh"]
    resources:
      limits:
        hugepages-1Gi: "1Gi"
        memory: "2Gi"
        cpu: "4000m"
      requests:
        hugepages-1Gi: "1Gi"
        memory: "2Gi"
        cpu: "4000m"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
  - name: tcpdump
    image: registry.example.com:5000/testpmd
    imagePullPolicy: Always
    command: ["/bin/bash", "-c", "while true; do if $ip link ls dp0; then tcpdump -nne -i dp0; fi ; echo 'Sleeping for 5 seconds'; sleep 5; done"]
    securityContext:
      privileged: true
    resources:
      limits:
        memory: "1Gi"
        cpu: "1000m"
      requests:
        memory: "1Gi"
        cpu: "1000m"
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages

